version: '3.5'

services:
  nginx-sp:  
    image: nginx-sp
    container_name: nginx-sp
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - secrets:/run/secrets:ro
    ports:
    - "81:80"
    - "443:443"
    environment:
      - NGINX_SERVER_NAME=service-provider
    entrypoint: /tmp/run_nginx.sh
    networks:
      - sp_proxy_net  
  sp-api:
    image: sp-api
    build:
      context: .
      dockerfile: ServiceProvider.API/Dockerfile
    entrypoint: bash -c "dotnet ServiceProvider.API.dll; tail -f /dev/null"
    expose:
      - "5000"  
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=QA
    networks:
      - sp_proxy_net
volumes:
  secrets:
networks:
  sp_proxy_net:
    name: sp_net
    ipam:
       driver: default
       config:
          - subnet: <CIDR>